antrian/urls.py
from django.urls import path
from . import views

app_name = 'antrian'

urlpatterns = [
    path('', views.antri, name='antri'),
    ]

homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'


urlpatterns = [
    path('', views.home, name='home'),
]

makanyu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('menu/', include('menu.urls')),
    path('pesan_makanan/', include('pesan_makanan.urls')),
    path('antrian/', include('antrian.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')), # new
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('menumakan/', views.menumakan, name='menumakan'),
    path('create/', views.menu_create, name='menu_create'),
    path('ajax_search/', views.search_menu, name='ajax_search')
    ]

pesan_makanan/urls.py
from django.urls import path
from . import views

app_name = 'pesan_makanan'

urlpatterns = [
    path('', views.pesan_makanan, name='pesan_makanan'),
]

registration/urls.py
from django.conf.urls import url
from registration import views

from django.urls import path

app_name = 'registration'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

antrian/models.py
from django.db import models
from pesan_makanan.models import PesanMakanan
# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

class Restaurant(models.Model):
    nama = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=50)
    alamat = models.CharField(max_length=50)
    gambar = models.ImageField(upload_to='images/')

        

menu/models.py
from django.db import models
# from django.contrib.auth.models import User
# Create your models here.
class Menu(models.Model):
	name = models.CharField(max_length=30)
	price = models.PositiveIntegerField()
	image = models.ImageField(upload_to='images/')

	def __str__(self):
		return self.name

class MenuDipesan(models.Model):
	menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
	amount = models.PositiveSmallIntegerField()

	def __str__(self):
		return str(self.menu)

class Pesan(models.Model):
    menu = models.ManyToManyField(MenuDipesan)

pesan_makanan/models.py
from django.db import models
from menu.models import Pesan 

# Create your models here.
class PesanMakanan(models.Model):
	# hari, tanggal, jam, nama kegiatan, tempat, dan kategori
	nama = models.CharField(max_length=20) #buat nama di adyssa dan munculin .idnya
	jumlah_harga = models.PositiveIntegerField() #gu
	pesanan = models.ForeignKey(Pesan, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return '{} {} {}'.format(self.nama, self.jumlah_harga, self.pesanan)

antrian/forms.py
from django import forms
from pesan_makanan.forms import PesanMakananForm

homepage/forms.py
from django import forms
from .models import Restaurant

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['nama', 'deskripsi', 'alamat', 'gambar']
        labels  = {
        'nama':'Nama Restoran', 
        'deskripsi':'Deskripsi Restoran', 
        'alamat':'Alamat Restoran', 
        'gambar':'Foto Restoran',
        }

        widgets = {
        'nama' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Rumah Makan Sederhana'}),
        'deskripsi' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Aneka Masakan Padang'}),
        'alamat' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text', 'placeholder' : 'Jl. Menuju Surga'}),

        }
    
        

menu/forms.py
from django import forms
from .models import Menu

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['name', 'price','image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class PesanForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for menu in Menu.objects.all():
			self.fields['menu_' + str(menu.id)] = forms.IntegerField(
				min_value=0,
				max_value=32767,
				initial=0,
			)

pesan_makanan/forms.py
from django import forms
from .models import PesanMakanan

class PesanMakananForm(forms.Form):
	nama = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'style':'border-radius:10px'})) #buat nama di adyssa dan munculin .idnya

antrian/views.py
from django.shortcuts import render, redirect
from menu.models import Pesan, MenuDipesan, Menu
from . import forms
from pesan_makanan.forms import PesanMakananForm
from pesan_makanan.models import PesanMakanan

def antri(request):
    listPesanan = PesanMakanan.objects.all()
    # for pesanan in listPesanan:
    #     print(pesanan.nama)
    #     print(pesanan.pesanan)
    
    return render(request, 'antri.html', {'antri' : listPesanan})

homepage/views.py
from django.shortcuts import render, redirect
from .forms import RestaurantForm
from .models import Restaurant

# Create your views here.


def home(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/home')
    else:
        form = RestaurantForm()


    temp = Restaurant.objects.all()
    
    return render(request, 'home.html', {'restaurant_list': temp,
                                         'ini_restaurant_form': form,
                                         'home_page' : True,})

menu/views.py
from django.shortcuts import render, redirect, Http404, get_object_or_404
from .models import Menu, Pesan, MenuDipesan
from django.urls import reverse
from . import forms
# Create your views here.

def menumakan(request):
	if request.method == 'POST':
		form_pesanan = forms.PesanForm(request.POST)
		if form_pesanan.is_valid():
			pesanan = Pesan()
			pesanan.save()
			counter = 0
			for key, value in form_pesanan.cleaned_data.items():
				if key[:5] == 'menu_' and value > 0:
					counter += 1
					menu_dipesan = MenuDipesan(menu=Menu.objects.get(id=int(key[5:])),
						amount=value)
					menu_dipesan.save()
					pesanan.menu.add(menu_dipesan)
			if counter != 0:
				return redirect(reverse('pesan_makanan:pesan_makanan'))
	else:
		form_pesanan = forms.PesanForm()

	semua_menu = Menu.objects.all()
	for menu in semua_menu:
		menu.form_field = form_pesanan['menu_' + str(menu.id)]

	return render(request, 'menumakan.html', {'menus':semua_menu, 'form_pesanan': form_pesanan})

def menu_create(request):
    form = forms.MenuForm(request.POST, request.FILES) 
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('menu:menumakan')
    else:
        form = forms.MenuForm()
    return render(request, 'menu_create.html', {'form': form})


def search_menu(request):
    if request.is_ajax():
        filtered = Menu.objects.filter(name__icontains=request.GET.get('q', ''))
        data = serializers.serialize('json', filtered)
        return HttpResponse(data, content_type='application/json')
    raise Http404()

pesan_makanan/views.py
from django.shortcuts import render, redirect
from .models import PesanMakanan
from menu.models import Pesan
from . import forms

# Create your views here.
def pesan_makanan(request):
	total = 0
	pesanan_menu = Pesan.objects.last() #pesanMakanan ubah dengan hasilnya 
	for pesanan in pesanan_menu.menu.all():
		total += pesanan.menu.price * pesanan.amount
	
	if request.method == 'POST':
		pesan_makanan = forms.PesanMakananForm(request.POST)
		if pesan_makanan.is_valid():
			PesanMakanan(nama=pesan_makanan.cleaned_data['nama'], 
				jumlah_harga=total, 
				pesanan=Pesan.objects.last()).save()
			return redirect('antrian:antri')
	else:
		print(request.method)
		pesan_makanan = forms.PesanMakananForm()
	
	return render(request, 'pesanMakanan.html', {'title': 'CEK PESANAN', 'menu': pesanan_menu, 'pesan_makanan': pesan_makanan, 'total': total}) 

antrian/templates/antri.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<html lang="en">


<head>
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <title> Antrian </title>
</head>
<body>
    <div class="row p-4">
    <div class = "col-md-12">
        <h1 id="judul">Ayam Penyet Strike</h1>
        <h2 id="text1">Spesialis Ayam Penyet</h2>
        <h2 id="text2">Jalan Akses UI No. 32 Depok, Jawa Barat</h2>
   </div>
</div>

<div class="row p-4">
    <div class="col-md-4">
        <img id="foto" src="{% static 'image/ayam-rica-rica.jpg' %}" width="300" height="200">
    </div>
    <div class="col-md-4">
        <img id="foto2" src="{% static 'image/ayam-goreng-mentega.jpg' %}" width="300" height="200">
    </div>
    <div class="col-md-4">
        <img align="left" src="{% static 'image/ayam-bakar-taliwang.jpg' %}" width="300" height="200">
    </div>
</div>
 
<div class="row p-4" id="menu">
    <div class="col-md-1 btn-group btn-group-toggle" data-toggle="buttons">
        <label class=" btn btn-warning active">
            <input type="radio" name="options" id="option1">Menu</input>
        </label>
        <label class="btn btn-default active">
            <input type="radio" name="options" id="option2">Antrian</input>
        </label>
    </div>
</div>

    <a href="{% url 'antrian:antri' %}"></a>
<div class="d-flex justify-content-center w-100 row text-center">
    <h1 id="judul">ANTRIAN</h1>
</div>
<div class="col-md-12 text-center">
    {% if antri %}
    <form action="" method="GET">
    <table style="font-size: 30px" cellpadding="70" border="0">
        <thead>
            <th style=" padding-top: 40px;padding-bottom: 0px">Name</th>
            <th style=" padding-top: 40px; padding-bottom: 0px">Pesanan</th>
        </thead>
        <tbody>
                {% csrf_token %}
                {% for pesanan in antri %}
                <div class="col-sm-4 text-center">
                    <tr>
                    <td> {{ pesanan.nama }} </td>
                    <td>
                        {% for makanan in pesanan.pesanan.menu.all %}
                        {{ makanan }}
                        {% endfor %}
                    </td>
                    </tr>
                </div>
                {% endfor %}
        </tbody>
    </table>

    </form>
    {% else %}
    <div class="no-menu margin-small">
        <h2>There is no queue yet</h2>
    </div>
    {% endif %}
</div>
{% endblock %}
</body>
</html>

makanyu/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="makanyu_logo.png" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel = "stylesheet" href="{% static 'css/base.css' %}"> 
    
    <!-- Slick for carousel -->
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    
    
    {% block css %}
    {% endblock css %}
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <!-- Slick for carousel -->
    
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
        
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    
    <script type="text/javascript" src="slick/slick.min.js"></script>
    
    {% block script %}
    {% endblock script %}
    
	<style>
		@font-face {
		    font-family: 'Kayak Sans';
		    src: url('{% static 'fonts/Kayak Sans Regular.otf' %} format("opentype")');
		}
		
		@font-face {
		    font-family: 'Kayak Sans';
		    font-weight: bold;
		    src: url('{% static 'fonts/Kayak Sans Bold.otf' %} format("opentype")');
		}

		@font-face {
		    font-family: 'Kayak Sans';
		    font-weight: lighter;
		    src: url('{% static 'fonts/Kayak Sans Light.otf' %} format("opentype")');
		}
	</style>
    
    
    
</head>
<body style="height: 100vh; background-color: white; font-family: Kayak Sans">
    <div class="bs-example">
        <nav class="navbar navbar-expand-sm navbar-light bg-white fixed-top shadow p-3 mb-5">
              <a class="navbar-brand" href="{% url 'homepage:home' %}">
                 <img src="{% static 'images/makanyu logo.png' %}" height="50px">
                </a>
                 
            
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                 
<!--
            {% if user.is_authenticated %}
                {{ user.username }}
            
            {% else %}
                <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav ml-auto">
                    <a href="#" class="nav-item nav-link">Masuk</a>
                    <button type="button" class="btn btn-primary"> Daftar </button>
                    
                    <a class="btn btn-outline-success" type="button" href="{% url 'logout' %}">Logout</a>
                </div>
              </div>
            {% endif %}

-->
              
            
            
             {% if user.is_authenticated %}
            
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <div class="nav-item nav-link">{{ user.username }}</div>
                    <button onclick="window.location.href='/accounts/logout'" class="btn btn-outline-warning" type="button">Keluar</button>
                </ul>
              </div>
            
            {% else %}
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <a href="{% url 'login' %}" class="nav-item nav-link">Masuk</a>
                    <button onclick="window.location.href='/accounts/signup'" class="btn btn-primary" type="button">Daftar</button>
                </ul>
              </div>
            {% endif %}
              
            
        </nav>
    </div>
    
    <div style="padding-top: 100px">
	{% block content %}
		<div style="text-align: center; position: relative; top: 36%; color: white;">
			<h1 style="font-size: 75px; margin: auto;">
				COMING SOON
			</h1>
			<h1 style="font-size: 50px; margin: auto; font-family: 'Kayak Sans'; font-weight: lighter;">
				Makanyu
			</h1>
		</div>
	{% endblock content %}
    </div>
    	
</body>
    
</html>

menu/templates/menu_create.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% block content %}
<body style="background-image: url('{% static 'image/background.png'%}')">

<div class="menu">
    <p class="font text-center" id="judul">Create Menu</p>
    <form action="{% url 'menu:menu_create' %}" method="POST" id = "post-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
                    <div class="col-sm-1"></div>
                        <div class="form-group col-sm-10">
                            {% for fields in form %}
                                {{ fields.label_tag }}
                                    <br>
                                {{ fields }}
                            {% endfor %}
                        </div>
                    </div>
                <div class="form-row">
            <div class="col-sm-1"></div>
        <input type="file" name="myfile">
        <input type="submit" class="btn btn-primary float-right" value="Submit">
    </form>      
</div>
</body>

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

menu/templates/menumakan.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row p-4">
    <div class = "col-md-12">
        <h1 id="judul">Ayam Penyet Strike</h1>
        <h2 id="text1">Spesialis Ayam Penyet</h2>
        <h2 id="text2">Jalan Akses UI No. 32 Depok, Jawa Barat</h2>
   </div>
</div>

<div class="row p-4">
    <div class="col-md-4">
        <img id="foto" src="{% static 'image/ayam-rica-rica.jpg' %}" width="300" height="200">
    </div>
    <div class="col-md-4">
        <img id="foto2" src="{% static 'image/ayam-goreng-mentega.jpg' %}" width="300" height="200">
    </div>
    <div class="col-md-4">
        <img align="left" src="{% static 'image/ayam-bakar-taliwang.jpg' %}" width="300" height="200">
    </div>
</div>
    <button type="button" class="btn btn-warning" onclick="window.location.href='/menu/create'">
      Add Menu</button> 
<div class="row p-4" id="menu">
    <div class="col-md-1 btn-group btn-group-toggle" data-toggle="buttons">
            <button type="button" class="btn btn-warning">Menu</button>
            <button type="button" class="btn btn-light">Antrian</button>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'js/jquerymenu.js' %}"></script>

<a href="{% url 'menu:menumakan' %}"></a>
<div class="d-flex justify-content-center w-100 row text-center">
    <h1 id="judul">MENU</h1>
</div>
<div class="col-md-12 text-center">
    <form method="POST">
      <div class="card mt-5">
        <input class="form-control" type="text" name="q" placeholder="Search for Menu">
      </div>

    {% if menus %}
    <table style="font-size: 30px" cellpadding="70" border="0">
        <thead>
            <th style=" padding-top: 40px;padding-bottom: 0px">Name</th>
            <th style=" padding-top: 40px; padding-bottom: 0px">Price</th>
        </thead>
        <tbody>
                {% csrf_token %}
                {% for menumakan in menus %}
                <div class="col-sm-4 text-center" id="test">
                    <tr>
                    <td> {{ menumakan.name }} </td>
                    <td> {{ menumakan.price }} </td>
                    <td> <img style="width: 300px" class="images"src="{{ menumakan.image.url }}"> </td>
                    <td>{{ menumakan.form_field }}</td>
                    </tr>
                </div>
                {% endfor %}
        </tbody>
    </table>
    <div class = 'col-md-12'>
        <div class = "w-100 d-flex justify-content-center form-group">
            <button class="btn btn-warning btn-primary" type="submit" >Pesan</button>
        </div>
    </div>
    </form>
    {% else %}
    <div class="no-menu margin-small">
        <h2>There's no menu yet</h2>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script>
$('form').on('click', 'button:not([type="submit"])', function(e){
  e.preventDefault();
})
var search_url = "{% url 'menu:ajax_search' %}"
</script>
<script src="{% static 'js/search.js' %}"></script>
{% endblock %}

menu/templates/search.html
<div class="menu">
  <h1>Pencarian</h1>
  <div class="container-fluid">
    {% for menumakan in search_result %}
    <div class="row align-items-center">
      <div class="col-6 col-md-2">
        <span class="name">{{ menumakan.name }}</span>
        <br>
        <span class="price">{{ menumakan.price }}</span>
      </div>
      <div class="col-6 col-md-2">
        <img src="{{ menumakan.image.url }}">
      </div>
      <div class="col-6 col-md-3">
        <div class="input-number position-relative">
          {{ menu.form_field }}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

pesan_makanan/templates/pesanMakanan.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div id="bg-blur" class="d-flex justify-content-center align-items-center w-100 h-100">
	<div id="kotak_pesanan" class="h-100 w-50"style=" background-color: white">
		<div class="p-4 h-100" id="list_pesanan">
			<h1 style="font-size: 50px">Pesanan Kamu</h1>
			<form style="font-size: 26px" method="POST">
				{% csrf_token %}
				<div>{{ pesan_makanan.nama.label_tag }}</div>
				<div>{{ pesan_makanan.nama }}</div>
				{% for menu_dipesan in menu.menu.all %}
				<div class="p-2 row">
					<div class="col-1">{{ menu_dipesan.amount }}</div>
					<div class="col-7">
						 {{ menu_dipesan.menu.name }} <br> 
						<!-- <span class="text-secondary"> deskirpsi </span> -->
					</div>
					<div class="col-4">Rp {{ menu_dipesan.menu.price | intcomma }} </div>
				</div>
				{% endfor %}
				<div class="p-2">
					<div><b>Total</b></div>
					<div><b>Rp {{ total | intcomma }} </b></div>
				</div>
				<div class="d-flex justify-content-center">
					<button onclick="goBack()" class="btn btn-primary shadow">Batal</button>
					<input class=" btn btn-primary shadow" type="submit" value="Pesan">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}

{% block script %}
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock script %}